//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozlite.Extensions.Security {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mozlite.Extensions.Security.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与 邮件已经被注册，请使用其他邮件地址！ 类似的本地化字符串。
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 激活&quot;[$site;]&quot;的账户 类似的本地化字符串。
        /// </summary>
        public static string Email_ActiveAccount {
            get {
                return ResourceManager.GetString("Email_ActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 [$name;] 先生/小姐：&lt;br/&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;你好&lt;br/&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;你还没有激活[$site;]网站注册的账户，点击链接（本链接24小时内有效）进行激活&lt;a href=&quot;[$link;]&quot; target=&quot;_blank&quot;&gt;[$link;]&lt;/a&gt;...&lt;br/&gt;&lt;br/&gt;
        ///&lt;div style=&quot;text-align:right; margin-right:10px&quot;&gt;[$site;]团队 敬上&lt;/div&gt;
        ///&lt;div style=&quot;text-align:right; margin-right:10px&quot;&gt;[$today;]&lt;/div&gt; 类似的本地化字符串。
        /// </summary>
        public static string Email_ActiveAccount_Body {
            get {
                return ResourceManager.GetString("Email_ActiveAccount_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 电子邮件不能为空！ 类似的本地化字符串。
        /// </summary>
        public static string EmailNotNull {
            get {
                return ResourceManager.GetString("EmailNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 密码和确认密码不一致！ 类似的本地化字符串。
        /// </summary>
        public static string PasswordAndConfirmPasswordNotEqual {
            get {
                return ResourceManager.GetString("PasswordAndConfirmPasswordNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 密码格式错误！ 类似的本地化字符串。
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 密码不能为空！ 类似的本地化字符串。
        /// </summary>
        public static string PasswordNotNull {
            get {
                return ResourceManager.GetString("PasswordNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 用户名非法，已经被禁用！ 类似的本地化字符串。
        /// </summary>
        public static string UserNameDisallowed {
            get {
                return ResourceManager.GetString("UserNameDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 用户名已经被注册，请使用其他邮件地址！ 类似的本地化字符串。
        /// </summary>
        public static string UserNameDuplicate {
            get {
                return ResourceManager.GetString("UserNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 用户名格式错误！ 类似的本地化字符串。
        /// </summary>
        public static string UserNameInvalid {
            get {
                return ResourceManager.GetString("UserNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 用户名称不能为空！ 类似的本地化字符串。
        /// </summary>
        public static string UserNameNotNull {
            get {
                return ResourceManager.GetString("UserNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 注册时间 类似的本地化字符串。
        /// </summary>
        public static string UserSorter_CreatedDate {
            get {
                return ResourceManager.GetString("UserSorter_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 最后登陆时间 类似的本地化字符串。
        /// </summary>
        public static string UserSorter_LastLoginDate {
            get {
                return ResourceManager.GetString("UserSorter_LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 名称 类似的本地化字符串。
        /// </summary>
        public static string UserSorter_Name {
            get {
                return ResourceManager.GetString("UserSorter_Name", resourceCulture);
            }
        }
    }
}
